import { ErrorInfo } from "@/types";

const errorData: ErrorInfo = {
  "id": "expiredtoken",
  "name": "ExpiredToken",
  "category": "aws",
  "badges": [
    "AWS STS",
    "CLI Error",
    "High Priority"
  ],
  "updatedAt": "June 29, 2026",
  "shortDescription": "This error occurs when the temporary security credentials provided by AWS STS (or AWS SSO/Identity Center) have expired.",
  "meanDescription": "An 'ExpiredToken' (or 'RequestExpired') error is raised when temporary security credentials generated by AWS Security Token Service (STS) or AWS IAM Identity Center exceed their expiration duration limit (standard lifespan spans from 15 minutes to 36 hours). Once expired, any subsequent API calls using the session token will be rejected by the AWS gateway.",
  "causes": [
    "Expired CLI/SDK session profile: AWS IAM Identity Center (SSO) login token or MFA session credentials have timed out.",
    "Assumed Role duration limit exceeded: The session credentials generated by 'sts:AssumeRole' have expired before the long-running script completed.",
    "System clock drift on client machine: Local machine system clock differs from AWS standard time, causing AWS to reject valid session tokens."
  ],
  "solutions": [
    "Re-authenticate using AWS CLI tools: Run 'aws sso login' or refresh credentials helper configurations.",
    "Configure longer session durations: Increase the 'DurationSeconds' parameter up to 12 hours inside AssumeRole configurations.",
    "Synchronize client system clock: Sync local clock using NTP configurations to ensure timestamps align with AWS."
  ],
  "example": {
    "title": "Syntax representation",
    "code": "An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired",
    "language": "text"
  },
  "exampleRequest": {
    "title": "Before (Triggering CLI command)",
    "code": "# Accessing AWS API using expired temporary session token\naws sts get-caller-identity",
    "language": "bash"
  },
  "exampleResponse": {
    "title": "Terminal Output Example",
    "code": "An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired\n$ echo $?\n254",
    "language": "bash"
  },
  "frameworkExamples": [
    {
      "name": "SSO Profile Config",
      "language": "ini",
      "description": "Configure the AWS CLI profile to utilize IAM Identity Center (SSO) credentials with automatic token cache refresh managers.",
      "code": "[profile developer-sso]\nsso_session = my-sso-session\nsso_account_id = 123456789012\nsso_role_name = DeveloperPowerUser\nregion = us-west-2\n\n[sso-session my-sso-session]\nsso_start_url = https://my-org.awsapps.com/start\nsso_region = us-west-2\nsso_registration_scopes = sso:account:access"
    },
    {
      "name": "AWS CLI SSO Login",
      "language": "bash",
      "description": "Trigger local session credential update flows using sso command helper tools.",
      "code": "# Force login to trigger browser validation and refresh credentials\n$ aws sso login --profile developer-sso"
    }
  ],
  "serverExamples": [
    {
      "name": "Linux",
      "language": "bash",
      "description": "Inspect cached SSO tokens and refresh credentials using the CLI.",
      "code": "# 1. List cached credentials files\nls ~/.aws/cli/cache/\n\n# 2. Check local system time synchronization\ntimedatectl status"
    },
    {
      "name": "Windows",
      "language": "powershell",
      "description": "Verify environment variable credentials overrides inside Windows nodes.",
      "code": "# 1. Inspect environment session variables\nGet-ChildItem Env: | Where-Object { $_.Name -like \"*AWS_SESSION_TOKEN*\" }\n\n# 2. Synchronize Windows system clock\nw32tm /resync"
    },
    {
      "name": "macOS",
      "language": "bash",
      "description": "Export session credentials overrides.",
      "code": "# Clear potential hardcoded stale environment keys\nunset AWS_ACCESS_KEY_ID\nunset AWS_SECRET_ACCESS_KEY\nunset AWS_SESSION_TOKEN"
    }
  ],
  "commonMistakes": [
    "Hardcoding `AWS_SESSION_TOKEN` inside continuous integration pipeline files (CI/CD workflows) where tokens decay quickly, locking builds out.",
    "Neglecting to adjust the IAM Role's Maximum CLI/API session duration attribute when requesting long role sessions (up to 12 hours) in STS calls."
  ],
  "prevention": [
    "Configure credentials provider chains inside SDK apps to auto-renew session certificates.",
    "Adopt AWS IAM Identity Center instead of long-lived access credentials profiles."
  ],
  "faq": [
    {
      "question": "What is an ExpiredToken error?",
      "answer": "This means the temporary access keys (AccessKeyId, SecretAccessKey, and SessionToken) you are using to authenticate were generated by AWS STS but have now expired. You need to get a new set of keys."
    },
    {
      "question": "How do I refresh credentials when using AWS IAM Identity Center (SSO)?",
      "answer": "Simply run: 'aws sso login'. This opens your browser to authenticate. Once logged in, the AWS CLI automatically updates your temporary credentials cache."
    },
    {
      "question": "Why do assumed roles expire after 1 hour?",
      "answer": "When you call 'sts:AssumeRole', the default session duration is 1 hour. If your application runs longer than this, you get an ExpiredToken error. You can specify a higher '--duration-seconds' value (up to 43200 seconds / 12 hours) when assuming the role, provided the role itself is configured to allow that duration."
    },
    {
      "question": "How does clock drift cause this error?",
      "answer": "AWS compares the signature timestamp on your request with its own server time. If your local system clock drifts by more than 5 minutes, AWS rejects your request, often showing an ExpiredToken or invalid signature error."
    }
  ],
  "helpfulResources": [
    {
      "name": "AWS STS Temporary Security Credentials guide",
      "url": "https://docs.aws.amazon.com/STS/latest/UserGuide/id_credentials_temp.html"
    }
  ],
  "relatedErrors": [
    "accessdeniedexception"
  ],
  "quickFix": {
    "causes": [
      "AWS IAM Identity Center (SSO) login token has expired",
      "Assumed STS role session duration limit has been exceeded",
      "Host node clock drift causes AWS gateway signature validation failures"
    ],
    "checklist": [
      "Run aws sso login to refresh SSO session profile credentials",
      "Check environment variables for stale AWS_SESSION_TOKEN values",
      "Increase duration-seconds parameters inside AssumeRole calls",
      "Confirm host node clock synchronization (timedatectl check)"
    ],
    "estimatedTime": "2 minutes"
  },
  "causesTable": [
    {
      "cause": "Expired AWS IAM Identity Center (SSO) login session (usually 8-12 hours)",
      "frequency": "⭐⭐⭐⭐⭐"
    },
    {
      "cause": "Assumed IAM Role token lease timeout (default 1 hour limit)",
      "frequency": "⭐⭐⭐⭐"
    },
    {
      "cause": "Client system clock drift causing premature token expiration",
      "frequency": "⭐⭐⭐"
    }
  ],
  "comments": [],
  "seoTitle": "How to Fix ExpiredToken in AWS (With Examples)",
  "seoDescription": "Encountering ExpiredToken in AWS? Discover what triggers this error, how to diagnose it, and the best practices to fix and prevent it from happening again."
};

export default errorData;
