import { ErrorInfo } from "@/types";

const errorData: ErrorInfo = {
  "id": "304-not-modified",
  "name": "304 Not Modified",
  "category": "http-status",
  "badges": [
    "HTTP Status Codes",
    "Redirection (3xx)",
    "common"
  ],
  "updatedAt": "today",
  "shortDescription": "Indicates that the resource has not been modified since the version specified by the request headers.",
  "meanDescription": "The HTTP 304 Not Modified redirection status code indicates that there is no need to re-transmit the requested resources. It is an implicit redirection to a cached local copy. This code is returned when conditional headers (e.g., If-None-Match, If-Modified-Since) verify no changes.",
  "causes": [
    "Client requests carrying cached ETag hashes matching server resource state ETag.",
    "Client requests with If-Modified-Since values newer than server last-modified timestamps."
  ],
  "solutions": [
    "Configure web servers to generate and compare ETag hashes correctly.",
    "Return the 304 code without any response body payload."
  ],
  "example": {
    "title": "Conditional Cache Request",
    "code": "GET /style.css HTTP/1.1\nHost: example.com\nIf-None-Match: \"etag-hash-123\"",
    "language": "http"
  },
  "exampleRequest": {
    "title": "Conditional Cache Request",
    "code": "GET /style.css HTTP/1.1\nHost: example.com\nIf-None-Match: \"etag-hash-123\"",
    "language": "http"
  },
  "exampleResponse": {
    "title": "Not Modified Response",
    "code": "HTTP/1.1 304 Not Modified\nETag: \"etag-hash-123\"\nCache-Control: public, max-age=3600\n\n(No message body content is sent)",
    "language": "http"
  },
  "frameworkExamples": [
    {
      "name": "Express",
      "language": "javascript",
      "description": "Express conditional caching using ETag middleware.",
      "code": "app.get('/data', (req, res) => {\n  const data = { id: 1 };\n  res.setHeader('ETag', 'hash-123');\n  if (req.headers['if-none-match'] === 'hash-123') {\n    return res.status(304).end();\n  }\n  res.json(data);\n});"
    },
    {
      "name": "Next.js",
      "language": "typescript",
      "description": "Setting Cache-Control headers inside Next.js routes.",
      "code": "export async function GET(request: Request) {\n  // Next.js static files handle 304 negotiation automatically\n  return new Response(null, { status: 304 });\n}"
    },
    {
      "name": "Django",
      "language": "python",
      "description": "Using django.views.decorators.http conditional decorators.",
      "code": "from django.views.decorators.http import condition\n# Django view using ETag decorators to return 304 automatically"
    },
    {
      "name": "Spring Boot",
      "language": "java",
      "description": "Using ShallowEtagHeaderFilter in Spring configurations.",
      "code": "@Bean\npublic Filter shallowEtagHeaderFilter() {\n    return new ShallowEtagHeaderFilter();\n}"
    }
  ],
  "serverExamples": [
    {
      "name": "Nginx",
      "language": "nginx",
      "description": "Nginx conditional header caching settings.",
      "code": "etag on;\nexpires 1h;"
    },
    {
      "name": "Apache",
      "language": "apache",
      "description": "Apache ETag and expires modules setup.",
      "code": "FileETag MTime Size\nExpiresActive On"
    }
  ],
  "commonMistakes": [
    "Sending a response body payload on a 304 response, causing connection errors.",
    "Miscalculating ETag values, resulting in clients getting stale cached assets."
  ],
  "prevention": [
    "Use server-level ETag filters (like Nginx etag on) to automate caching validations.",
    "Verify cache headers (Cache-Control, Last-Modified) are configured consistently."
  ],
  "faq": [
    {
      "question": "Does a 304 response contain a body?",
      "answer": "No. A 304 response must not contain a message body. Any headers that would describe the body (like Content-Length) should refer to the cached representation."
    },
    {
      "question": "What triggers a 304 response?",
      "answer": "A 304 is triggered when the client sends conditional validation headers (If-None-Match or If-Modified-Since) and the server verifies that the resource state hasn't changed."
    },
    {
      "question": "How does 304 Not Modified help server performance?",
      "answer": "It eliminates the need to download large files again, dramatically reducing network bandwidth consumption and speeding up page rendering."
    },
    {
      "question": "What is an ETag?",
      "answer": "An Entity Tag (ETag) is a unique string hash generated by the server representing a specific version of a resource file."
    }
  ],
  "helpfulResources": [
    {
      "name": "MDN Web Docs",
      "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304"
    },
    {
      "name": "RFC 7232 – Section 4.1",
      "url": "https://datatracker.ietf.org/doc/html/rfc7232#section-4.1"
    }
  ],
  "relatedErrors": [
    "200-ok"
  ],
  "comments": [],
  "quickFix": {
    "causes": [
      "Client requests carrying cached ETag",
      "Client requests with If-Modified-Since values"
    ],
    "checklist": [
      "Configure web servers to generate",
      "Return the 304 code without"
    ],
    "estimatedTime": "3 minutes"
  },
  "causesTable": [
    {
      "cause": "Client requests carrying cached ETag",
      "frequency": "⭐⭐⭐⭐⭐"
    },
    {
      "cause": "Client requests with If-Modified-Since values",
      "frequency": "⭐⭐⭐⭐"
    }
  ],
  "seoTitle": "Troubleshoot 304 Not Modified — HTTP Error Guide",
  "seoDescription": "Getting 304 Not Modified in HTTP? This guide covers why it happens, common causes, quick fix checklists, and step-by-step solutions with code examples to fix."
};

export default errorData;
