"use client";

import React, { useState } from "react";
import Link from "next/link";
import styles from "./page.module.css";

export default function JwtDecoderPage() {
  const [token, setToken] = useState("");
  const [header, setHeader] = useState<any>(null);
  const [payload, setPayload] = useState<any>(null);
  const [signature, setSignature] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const base64UrlDecode = (str: string): string => {
    let base64 = str.replace(/-/g, "+").replace(/_/g, "/");
    const pad = base64.length % 4;
    if (pad) {
      if (pad === 1) throw new Error("Invalid base64 string");
      base64 += new Array(5 - pad).join("=");
    }
    const decoded = atob(base64);
    try {
      return decodeURIComponent(
        Array.prototype.map
          .call(decoded, (c: string) => "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2))
          .join("")
      );
    } catch {
      return decoded;
    }
  };

  const faqItems = [
    {
      question: "Is client-side decoding safe for sensitive JWT keys?",
      answer: "Yes, absolutely. All decoding is completed locally using your browser's native window.atob engine. No strings or headers are sent to external systems, ensuring absolute credentials security."
    },
    {
      question: "Does this tool verify the signature of the token?",
      answer: "No. Client-side decoding only extracts the payload and header parameters. Cryptographic verification of signatures requires matching secret keys and public certificates which must only exist in your backend API servers."
    },
    {
      question: "What standard algorithms are supported?",
      answer: "Our decoder parses tokens generated by any standard algorithms including HS256, HS384, HS512, RS256, RS384, RS512, and ES256."
    },
    {
      question: "Why are timestamps shown as dates?",
      answer: "JSON Web Tokens store times (like exp, iat, and nbf) as Unix epoch integers. Our tool translates these values into your browser's local timezone format for quick troubleshooting."
    }
  ];

  const handleDecode = (rawToken: string) => {
    const cleanToken = rawToken.trim();
    setToken(cleanToken);

    if (!cleanToken) {
      setHeader(null);
      setPayload(null);
      setSignature("");
      setError(null);
      return;
    }

    const parts = cleanToken.split(".");
    if (parts.length !== 3) {
      setError("Invalid JWT format: A token must consist of exactly 3 parts separated by dots.");
      setHeader(null);
      setPayload(null);
      setSignature("");
      return;
    }

    try {
      const decodedHeader = JSON.parse(base64UrlDecode(parts[0]));
      const decodedPayload = JSON.parse(base64UrlDecode(parts[1]));
      
      setHeader(decodedHeader);
      setPayload(decodedPayload);
      setSignature(parts[2]);
      setError(null);
    } catch (err: any) {
      setError(err.message || "Failed to decode JWT base64 segments. Ensure the payload is valid Base64Url encoding.");
      setHeader(null);
      setPayload(null);
      setSignature("");
    }
  };

  const handleLoadSample = () => {
    const sampleHeaderObj = { alg: "HS256", typ: "JWT" };
    const samplePayloadObj = {
      iss: "https://auth.errorcrate.com",
      sub: "usr_01j2h98412",
      name: "Harsha Pyla",
      roles: ["admin", "developer"],
      iat: Math.floor(Date.now() / 1000) - 300,
      exp: Math.floor(Date.now() / 1000) + 3600,
    };

    const urlEncode = (obj: any) => {
      const json = JSON.stringify(obj);
      return btoa(json)
        .replace(/=/g, "")
        .replace(/\+/g, "-")
        .replace(/\//g, "_");
    };

    const encHeader = urlEncode(sampleHeaderObj);
    const encPayload = urlEncode(samplePayloadObj);
    const mockSignature = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
    
    const sampleToken = `${encHeader}.${encPayload}.${mockSignature}`;
    handleDecode(sampleToken);
  };

  const handleClear = () => {
    setToken("");
    setHeader(null);
    setPayload(null);
    setSignature("");
    setError(null);
  };

  const highlightJson = (jsonObj: any) => {
    if (!jsonObj) return null;
    const jsonStr = JSON.stringify(jsonObj, null, 2);
    
    const escaped = jsonStr
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

    const highlighted = escaped.replace(
      /("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+-]?\d+)?)/g,
      (match) => {
        let cls = styles.jsonNumber;
        if (/^"/.test(match)) {
          if (/:$/.test(match)) {
            cls = styles.jsonKey;
          } else {
            cls = styles.jsonString;
          }
        } else if (/true|false/.test(match)) {
          cls = styles.jsonBool;
        } else if (/null/.test(match)) {
          cls = styles.jsonNull;
        }

        if (cls === styles.jsonKey) {
          const cleanKey = match.slice(0, -1);
          return `<span class="${cls}">${cleanKey}</span>:`;
        }
        return `<span class="${cls}">${match}</span>`;
      }
    );

    return (
      <pre
        dangerouslySetInnerHTML={{ __html: highlighted }}
        className={styles.codePre}
      />
    );
  };

  const formatTimestamp = (ts: any) => {
    if (typeof ts !== "number") return "Invalid Timestamp";
    return new Date(ts * 1000).toLocaleString();
  };

  const checkExpiry = (exp: any) => {
    if (typeof exp !== "number") return null;
    const now = Math.floor(Date.now() / 1000);
    if (now > exp) {
      const diffMin = Math.floor((now - exp) / 60);
      return { expired: true, text: `Expired ${diffMin} minutes ago` };
    } else {
      const diffMin = Math.floor((exp - now) / 60);
      return { expired: false, text: `Active (Expires in ${diffMin} minutes)` };
    }
  };

  const expStatus = payload && payload.exp ? checkExpiry(payload.exp) : null;

  const relatedTools = [
    { name: "JSON Formatter", href: "/tools/json-formatter" },
    { name: "JWT Decoder", href: "/tools/jwt-decoder", active: true },
    { name: "Regex Tester", href: "/tools/regex-tester" },
    { name: "UUID Generator", href: "/tools/uuid-generator" },
    { name: "SQL Formatter", href: "/tools/sql-formatter" },
    { name: "YAML Validator", href: "/tools/yaml-validator" },
    { name: "Cron Builder", href: "/tools/cron-builder" },
    { name: "Timestamp Converter", href: "/tools/timestamp-converter" }
  ];

  return (
    <div className={styles.container}>
      <div className={styles.breadcrumbs}>
        <Link href="/tools" style={{ color: "var(--text-muted)", textDecoration: "none", transition: "color 0.2s" }} onMouseEnter={(e) => (e.currentTarget.style.color = "var(--accent-orange)")} onMouseLeave={(e) => (e.currentTarget.style.color = "var(--text-muted)")}>Developer Utilities</Link>
        <span style={{ color: "var(--text-muted)", margin: "0 8px" }}>&gt;</span>
        <span className={styles.breadcrumbActive}>Decoder</span>
      </div>
      
      <div className={styles.titleBlock}>
        <h1 className={styles.title}>Secure JWT Token Decoder</h1>
        <p className={styles.subtitle}>
          Decode JSON Web Tokens (JWT) client-side instantly. Extract token headers, payload claims, and check expiry status. Done entirely locally.
        </p>
      </div>

      {/* Error Box */}
      {error && (
        <div className={styles.errorBox}>
          <span>❌</span>
          <div>
            <strong>Validation Error:</strong> {error}
          </div>
        </div>
      )}

      {/* Workspace */}
      <div className={styles.workspace}>
        {/* Token Input Column */}
        <div className={styles.editorPane}>
          <div className={styles.paneHeader}>
            <span className={styles.paneTitle}>Paste JWT Token String</span>
            <div className={styles.paneActionRow}>
              <button onClick={handleLoadSample} className={styles.paneBtn}>
                Load Sample
              </button>
              <button onClick={handleClear} className={styles.paneBtn}>
                Clear
              </button>
            </div>
          </div>
          <textarea
            className={styles.textarea}
            placeholder="Paste your base64-encoded JWT token here (header.payload.signature)..."
            value={token}
            onChange={(e) => handleDecode(e.target.value)}
          />
        </div>

        {/* Decoded Output Column */}
        <div className={styles.outputPane}>
          {header && payload ? (
            <>
              {/* Header block */}
              <div className={styles.decodedBlock}>
                <div className={styles.blockHeader}>
                  <span className={styles.blockTitle}>Decoded Header</span>
                  <span className={`${styles.blockBadge} ${styles.header}`}>Metadata</span>
                </div>
                {highlightJson(header)}
              </div>

              {/* Payload block */}
              <div className={styles.decodedBlock}>
                <div className={styles.blockHeader}>
                  <span className={styles.blockTitle}>Decoded Payload (Claims)</span>
                  <span className={`${styles.blockBadge} ${styles.payload}`}>Claims</span>
                </div>
                {highlightJson(payload)}
                
                {/* Standard Timestamp Inspection */}
                {(payload.exp || payload.iat || payload.nbf) && (
                  <div className={styles.claimsTable}>
                    <span className={styles.claimsTitle}>Standard Claims Inspector</span>
                    {payload.iat && (
                      <div className={styles.claimRow}>
                        <span className={styles.claimName}>iat</span>
                        <span className={styles.claimVal}>
                          Issued At: {formatTimestamp(payload.iat)}
                        </span>
                      </div>
                    )}
                    {payload.nbf && (
                      <div className={styles.claimRow}>
                        <span className={styles.claimName}>nbf</span>
                        <span className={styles.claimVal}>
                          Not Before: {formatTimestamp(payload.nbf)}
                        </span>
                      </div>
                    )}
                    {payload.exp && (
                      <div className={styles.claimRow}>
                        <span className={styles.claimName}>exp</span>
                        <span className={styles.claimVal}>
                          Expiration Time: {formatTimestamp(payload.exp)}
                          {expStatus && (
                            <span className={expStatus.expired ? styles.expiredText : styles.activeText}>
                              ({expStatus.text})
                            </span>
                          )}
                        </span>
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* Signature block */}
              <div className={styles.decodedBlock}>
                <div className={styles.blockHeader}>
                  <span className={styles.blockTitle}>Signature Section</span>
                  <span className={`${styles.blockBadge} ${styles.signature}`}>HMAC/RSA</span>
                </div>
                <pre className={styles.codePre} style={{ color: "#94a3b8", fontStyle: "italic", whiteSpace: "pre-wrap", wordBreak: "break-all" }}>
                  {signature ? signature : "// Signature omitted or empty"}
                </pre>
              </div>
            </>
          ) : (
            <div className={styles.outputPlaceholder}>
              Paste a valid JWT token in the left panel to inspect its contents.
            </div>
          )}
        </div>
      </div>

      {/* Accordion FAQ Section */}
      <section className={styles.faqSection}>
        <h2 className={styles.faqHeading}>Frequently Asked Questions</h2>
        <div className={styles.faqContainer}>
          {faqItems.map((item, idx) => (
            <div key={idx} className={styles.faqItem}>
              <button
                onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                className={styles.faqQuestion}
              >
                <span>{item.question}</span>
                <span className={`${styles.faqIcon} ${openFaq === idx ? styles.faqIconExpanded : ""}`}>
                  +
                </span>
              </button>
              {openFaq === idx && (
                <div className={styles.faqAnswer}>
                  {item.answer}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* AdSense SEO & Sidebar Columns */}
      <section className={styles.seoSection}>
        {/* Rich Explanatory Content */}
        <div className={styles.seoContent}>
          <h2 className={styles.seoHeading}>What is a JSON Web Token (JWT)?</h2>
          <p className={styles.seoParagraph}>
            JSON Web Tokens (JWT) are an open, industry-standard RFC 7519 method for representing claims securely between two parties. JWTs are compact, URL-safe, and commonly used for stateless authorization handshakes, Single Sign-On (SSO) headers, and microservice contexts.
          </p>

          <h3 className={styles.seoHeading} style={{ fontSize: "1.2rem" }}>Structure of a JWT Token</h3>
          <p className={styles.seoParagraph}>
            A JWT is composed of three distinct base64url-encoded parts separated by dots (<code>.</code>):
          </p>
          <ul className={styles.seoList}>
            <li className={styles.seoListItem}>
              <strong>Header (Red):</strong> Declares the token type (typically <code>JWT</code>) and the cryptographic signing algorithm in use (e.g. <code>HS256</code> or <code>RS256</code>).
            </li>
            <li className={styles.seoListItem}>
              <strong>Payload (Blue):</strong> Contains the claims. Claims are statements about an entity (typically, the authenticated user) and additional metadata (such as expiration timestamps).
            </li>
            <li className={styles.seoListItem}>
              <strong>Signature (Green):</strong> Formed by hashing the encoded header, payload, and a secret key using the specified algorithm to ensure that the token was not altered in transit.
            </li>
          </ul>

          <h3 className={styles.seoHeading} style={{ fontSize: "1.2rem" }}>JWT Security Warning</h3>
          <p className={styles.seoParagraph}>
            It is critical to note that Base64Url encoding is <strong>not encryption</strong>. A JWT is simply serialized and can be read by anyone who intercepts it. You must never place sensitive information (like user passwords or API credentials keys) in the payload claims. Furthermore, while client-side decoders reveal token values, you must verify signatures cryptographically inside your backend application server using secret keys before trusting their contents.
          </p>
        </div>

        {/* Sidebar Navigation */}
        <div className={styles.sidebarCol}>
          <div className={styles.sidebarCard}>
            <h3 className={styles.sidebarTitle}>Developer Utilities</h3>
            <div className={styles.toolsList}>
              {relatedTools.map((tool) => (
                <Link
                  key={tool.name}
                  href={tool.href}
                  className={`${styles.toolLink} ${tool.active ? styles.activeToolLink : ""}`}
                >
                  <span>{tool.name}</span>
                  <span className={styles.toolLinkArrow}>&rarr;</span>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
